package com.example.bank.mapper;

import java.util.UUID;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingConstants;

import com.example.bank.api.dto.resp.TransactionResponse;
import com.example.bank.domain.AccountTransaction;
import com.example.bank.event.WithdrawalEvent;
import com.example.bank.model.TransactionEntity;

/**
 * The only crossing point between persistence, domain, dto and event objects
 * (anti-corruption boundary) — all implementations generated by MapStruct.
 */
@Mapper(componentModel = MappingConstants.ComponentModel.SPRING, imports = UUID.class)
public interface TransactionMapper {

	/** Persistence → domain: {@code id→transactionId}, {@code createdAt→occurredAt}; {@code accountId} maps by name. */
	@Mapping(target = "transactionId", source = "id")
	@Mapping(target = "occurredAt", source = "createdAt")
	AccountTransaction toAccountTransaction(TransactionEntity entity);

	/** Domain → controller-boundary dto, field-for-field. */
	TransactionResponse toTransactionResponse(AccountTransaction transaction);

	@Mapping(target = "eventId", expression = "java(UUID.randomUUID())")
	@Mapping(target = "status", constant = "SUCCESSFUL")
	/** Domain → integration event: fresh {@code eventId}, status fixed to SUCCESSFUL (preserved contract). */
	WithdrawalEvent toWithdrawalEvent(AccountTransaction transaction);
}
